services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/e-commerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2012001
    depends_on:
      - db

  frontend:
    
    build:
      context: ./frontend
      dockerfile: Dockerfile
      
      
    ports:
      - 3000:80
    depends_on:
      - backend
      
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=2012001
      - MYSQL_DATABASE=e-commerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

